"TableToKeyValues"
{
	"1"
	{
		"tooltip"		"Bushes & Trees"
		"Models"
		{
			"1"		"models/props_foliage/tree_springers_01a-lod.mdl"
			"2"		"models/props_foliage/tree_springers_01a.mdl"
			"3"		"models/props_foliage/tree_springers_card_01_skybox.mdl"
			"4"		"models/props_foliage/bramble001a.mdl"
			"5"		"models/props_foliage/cattails.mdl"
			"6"		"models/props_foliage/driftwood_01a.mdl"
			"7"		"models/props_foliage/driftwood_02a.mdl"
			"8"		"models/props_foliage/driftwood_03a.mdl"
			"9"		"models/props_foliage/driftwood_clump_01a.mdl"
			"10"		"models/props_foliage/driftwood_clump_02a.mdl"
			"11"		"models/props_foliage/driftwood_clump_03a.mdl"
			"12"		"models/props_foliage/ivy_01.mdl"
			"13"		"models/props_foliage/oak_tree01.mdl"
			"14"		"models/props_foliage/shrub_01a.mdl"
			"15"		"models/props_foliage/tree_cliff_01a.mdl"
			"16"		"models/props_foliage/tree_cliff_02a.mdl"
			"17"		"models/props_foliage/tree_deciduous_01a.mdl"
			"18"		"models/props_foliage/tree_deciduous_03a.mdl"
			"19"		"models/props_foliage/tree_deciduous_03b.mdl"
			"20"		"models/props_foliage/tree_poplar_01.mdl"
		}
		"icon"		"icon16/world.png"
		"name"		"Foliage"
	}
	"2"
	{
		"tooltip"		"Fences & Useful Door Props"
		"Models"
		{
			"1"		"models/props_c17/fence03a.mdl"
			"2"		"models/props_c17/fence02b.mdl"
			"3"		"models/props_c17/fence01b.mdl"
			"4"		"models/props_c17/gate_door01a.mdl"
			"5"		"models/props_c17/gate_door02a.mdl"
			"6"		"models/props_building_details/Storefront_Template001a_Bars.mdl"
			"7"		"models/props_borealis/borealis_door001a.mdl"
			"8"		"models/props_wasteland/interior_fence001g.mdl"
			"9"		"models/props_wasteland/interior_fence002d.mdl"
			"10"		"models/props_wasteland/wood_fence01a.mdl"
			"11"		"models/props_lab/blastdoor001a.mdl"
			"12"		"models/props_lab/blastdoor001b.mdl"
			"13"		"models/props_lab/blastdoor001c.mdl"
			"14"		"models/props_wasteland/wood_fence02a.mdl"
			"15"		"models/props_wasteland/prison_celldoor001b.mdl"
			"16"		"models/props_interiors/ElevatorShaft_Door01a.mdl"
			"17"		"models/props_debris/metal_panel01a.mdl"
			"18"		"models/props_debris/metal_panel02a.mdl"
			"19"		"models/props_doors/door03_slotted_left.mdl"
			"20"		"models/props_interiors/VendingMachineSoda01a_door.mdl"
			"21"		"models/props_wasteland/interior_fence002e.mdl"
			"22"		"models/props_interiors/refrigeratorDoor01a.mdl"
			"23"		"models/props_c17/door01_left.mdl"
			"24"		"models/props_c17/door02_double.mdl"
			"25"		"models/props_c17/gravestone_coffinpiece001a.mdl"
			"26"		"models/props_c17/gravestone_coffinpiece002a.mdl"
			"27"		"models/props_junk/TrashDumpster02b.mdl"
		}
		"icon"		"icon16/link_break.png"
		"name"		"Gates"
	}
	"3"
	{
		"tooltip"		"Broken Walls & Debris"
		"Models"
		{
			"1"		"models/props_debris/plaster_wall001a.mdl"
			"2"		"models/props_debris/plaster_wall002a.mdl"
			"3"		"models/props_debris/walldestroyed06b.mdl"
			"4"		"models/props_debris/walldestroyed07b.mdl"
			"5"		"models/props_debris/walldestroyed05a.mdl"
			"6"		"models/props_debris/tile_wall001a.mdl"
			"7"		"models/props_debris/tile_wall001a_base.mdl"
			"8"		"models/lostcoast/props_monastery/destroyed_walls02.mdl"
			"9"		"models/lostcoast/props_monastery/destroyed_walls03.mdl"
			"10"		"models/props_buildings/collapsedbuilding01awall.mdl"
			"11"		"models/props_debris/concrete_section128wall001a.mdl"
			"12"		"models/props_debris/concrete_section128wall001b.mdl"
			"13"		"models/props_debris/concrete_section128wall001c.mdl"
			"14"		"models/props_debris/concrete_section128wall002a.mdl"
			"15"		"models/props_debris/concrete_wall01a.mdl"
			"16"		"models/props_debris/concrete_wall02a.mdl"
			"17"		"models/props_debris/tile_wall001a_core.mdl"
			"18"		"models/props_debris/wall001a_base.mdl"
			"19"		"models/props_debris/walldestroyed01a.mdl"
			"20"		"models/props_debris/walldestroyed02a.mdl"
			"21"		"models/props_debris/walldestroyed03a.mdl"
			"22"		"models/props_debris/walldestroyed08a.mdl"
			"23"		"models/props/cs_militia/bathroomwallhole01_tile.mdl"
			"24"		"models/props/cs_militia/bathroomwallhole01_wood_broken_01.mdl"
			"25"		"models/props/cs_militia/bathroomwallhole01_wood_broken.mdl"
			"26"		"models/props/cs_militia/wallconcretehole.mdl"
			"27"		"models/props_debris/building_brokenexterior001a.mdl"
			"28"		"models/props_debris/building_brokenexterior001b.mdl"
			"29"		"models/props_debris/building_brokenexterior001c.mdl"
			"30"		"models/props_debris/building_brokenexterior002a.mdl"
			"31"		"models/props_debris/building_brokenexterior002b.mdl"
			"32"		"models/props_debris/building_brokenexterior002c.mdl"
			"33"		"models/props_debris/concrete_spawnhole001a.mdl"
			"34"		"models/props_debris/concrete_spawnplug001a.mdl"
			"35"		"models/props_debris/concrete_wall01a.mdl"
			"36"		"models/props_debris/concrete_wall02a.mdl"
			"37"		"models/props_debris/destroyedceiling01a.mdl"
			"38"		"models/props_debris/destroyedceiling01b.mdl"
			"39"		"models/props_debris/destroyedceiling01c.mdl"
			"40"		"models/props_debris/destroyedceiling01d.mdl"
			"41"		"models/props_debris/broken_floor001a.mdl"
			"42"		"models/props_debris/broken_pile001a.mdl"
			"43"		"models/props_debris/barricade_short01a.mdl"
			"44"		"models/props_debris/barricade_short02a.mdl"
			"45"		"models/props_debris/barricade_short03a.mdl"
			"46"		"models/props_debris/barricade_short04a.mdl"
			"47"		"models/props_debris/barricade_tall01a.mdl"
			"48"		"models/props_debris/barricade_tall02a.mdl"
			"49"		"models/props_debris/barricade_tall03a.mdl"
			"50"		"models/props_debris/barricade_tall04a.mdl"
			"51"		"models/props_debris/building_brokenwindow001a.mdl"
			"52"		"models/props_debris/building_brokenwindow001b.mdl"
			"53"		"models/props_unique/zombiebreakwallcoreframe01_dm.mdl"
		}
		"icon"		"icon16/house.png"
		"name"		"Wall Pieces"
	}
	"4"
	{
		"tooltip"		"Dead Corpses & Barbed Wire (Origins)"
		"Models"
		{
			"1"		"models/nzprops/origins/barbwire_blockade.mdl"
			"2"		"models/nzprops/origins/barbwire_long.mdl"
			"3"		"models/nzprops/origins/barbwire_gate.mdl"
			"4"		"models/nzprops/origins/barbwire_tube.mdl"
			"5"		"models/nzprops/origins/sandbag_blockade.mdl"
			"6"		"models/nzprops/origins/originscorpse01.mdl"
			"7"		"models/nzprops/origins/originscorpse02.mdl"
			"8"		"models/nzprops/origins/originscorpse03.mdl"
			"9"		"models/nzprops/origins/originscorpse04.mdl"
			"10"		"models/nzprops/origins/originscorpse04stick.mdl"
			"11"		"models/nzprops/origins/originscorpse05.mdl"
			"12"		"models/nzprops/origins/originscorpse05stick.mdl"
			"13"		"models/props_unique/wooden_barricade.mdl"
			"14"		"models/props_wasteland/barricade002a.mdl"
			"15"		"models/props_wasteland/barricade001a.mdl"
			"16"		"models/props_c17/concrete_barrier001a.mdl"
			"17"		"models/props_fortifications/concrete_barrier001_128_reference.mdl"
			"18"		"models/props_fortifications/concrete_barrier001_96_reference.mdl"
			"19"		"models/props_phx/construct/concrete_barrier00.mdl"
			"20"		"models/props_phx/construct/concrete_barrier01.mdl"
			"21"		"models/props_fortifications/barricade_razorwire001_128_reference.mdl"
			"22"		"models/props_fortifications/concrete_block001_128_reference.mdl"
			"23"		"models/props_fortifications/concrete_wall001_140_reference.mdl"
			"24"		"models/props_fortifications/police_barrier001_128_reference.mdl"
			"25"		"models/props_fortifications/traffic_barrier001.mdl"
			"26"		"models/props_fortifications/concrete_barrier001_96_reference.mdl"
			"27"		"models/props_fortifications/concrete_barrier001_96_reference.mdl"
			"28"		"models/props_fortifications/concrete_barrier001_96_reference.mdl"
		}
		"icon"		"icon16/bomb.png"
		"name"		"Apocalyptic"
	}
	"5"
	{
		"tooltip"		"Foggy Light Effect Props"
		"Models"
		{
			"1"		"models/effects/vol_light.mdl"
			"2"		"models/effects/vol_light01.mdl"
			"3"		"models/effects/vol_light02.mdl"
			"4"		"models/effects/vol_light128x128.mdl"
			"5"		"models/effects/vol_light128x256.mdl"
			"6"		"models/effects/vol_light128x384.mdl"
			"7"		"models/effects/vol_light128x512.mdl"
			"8"		"models/effects/vol_light256x512.mdl"
			"9"		"models/effects/vol_light64x128.mdl"
			"10"		"models/effects/vol_light64x256.mdl"
			"11"		"models/effects/lightshaft/lightshaft_2fortspawnext.mdl"
			"12"		"models/effects/lightshaft/lightshaft_window01.mdl"
			"13"		"models/lostcoast/effects/vollight_stainedglass.mdl"
			"14"		"models/props/cs_militia/bridgelight.mdl"
		}
		"icon"		"icon16/shading.png"
		"name"		"Light Effects"
	}
	"6"
	{
		"tooltip"		"Cabinets, Shelves, Urban Props"
		"Models"
		{
			"1"		"models/props_borealis/bluebarrel001.mdl"
			"2"		"models/props_interiors/Furniture_shelf01a.mdl"
			"3"		"models/props_junk/TrashDumpster02.mdl"
			"4"		"models/props_interiors/VendingMachineSoda01a.mdl"
			"5"		"models/props_wasteland/laundry_dryer001.mdl"
			"6"		"models/props_wasteland/laundry_dryer002.mdl"
			"7"		"models/props_wasteland/kitchen_stove002a.mdl"
			"8"		"models/props_wasteland/controlroom_storagecloset001b.mdl"
			"9"		"models/props_wasteland/medbridge_post01.mdl"
			"10"		"models/props_c17/signpole001.mdl"
			"11"		"models/props_trainstation/traincar_seats001.mdl"
			"12"		"models/props_vehicles/carparts_door01a.mdl"
			"13"		"models/props_lab/securitybank.mdl"
			"14"		"models/props_lab/reciever_cart.mdl"
			"15"		"models/props_lab/crematorcase.mdl"
			"16"		"models/props_lab/corkboard002.mdl"
			"17"		"models/props_lab/corkboard001.mdl"
			"18"		"models/props_lab/Cleaver.mdl"
			"19"		"models/props_lab/cactus.mdl"
			"20"		"models/props_trainstation/payphone001a.mdl"
			"21"		"models/props_lab/workspace003.mdl"
			"22"		"models/props_lab/workspace004.mdl"
			"23"		"models/props_lab/workspace002.mdl"
			"24"		"models/props_lab/workspace001.mdl"
			"25"		"models/props_lab/tpplugholder.mdl"
			"26"		"models/props_lab/tpplugholder_single.mdl"
			"27"		"models/props_lab/tpplug.mdl"
			"28"		"models/props_lab/servers.mdl"
			"29"		"models/props_vehicles/carparts_tire01a.mdl"
			"30"		"models/props_combine/combine_monitorbay.mdl"
			"31"		"models/props_combine/combine_interface001.mdl"
			"32"		"models/props_combine/combine_intmonitor001.mdl"
			"33"		"models/props_combine/CombineThumper002.mdl"
			"34"		"models/props_combine/CombineThumper001a.mdl"
			"35"		"models/props_combine/breendesk.mdl"
			"36"		"models/props_combine/combine_barricade_short02a.mdl"
			"37"		"models/props_combine/combine_bridge_b.mdl"
			"38"		"models/props_combine/combine_fence01a.mdl"
			"39"		"models/props_combine/combine_fence01b.mdl"
			"40"		"models/props_combine/weaponstripper.mdl"
			"41"		"models/nzprops/zombies_power_lever.mdl"
			"42"		"models/nzprops/zombies_power_lever_handle.mdl"
			"43"		"models/nzprops/zombies_power_lever_short.mdl"
			"44"		"models/props_c17/canister01a.mdl"
			"45"		"models/props_c17/canister02a.mdl"
			"46"		"models/props_c17/canister_propane01a.mdl"
			"47"		"models/props_c17/bench01a.mdl"
			"48"		"models/props_c17/chair02a.mdl"
			"49"		"models/props_c17/concrete_barrier001a.mdl"
			"50"		"models/props_c17/FurnitureChair001a.mdl"
			"51"		"models/props_c17/FurnitureCouch001a.mdl"
			"52"		"models/props_c17/FurnitureCouch002a.mdl"
			"53"		"models/props_c17/FurnitureCupboard001a.mdl"
			"54"		"models/props_c17/FurnitureDrawer001a.mdl"
			"55"		"models/props_c17/FurnitureDrawer002a.mdl"
			"56"		"models/props_c17/FurnitureDresser001a.mdl"
			"57"		"models/props_c17/FurnitureFridge001a.mdl"
			"58"		"models/props_c17/FurnitureRadiator001a.mdl"
			"59"		"models/props_c17/FurnitureShelf001a.mdl"
			"60"		"models/props_c17/furnitureStove001a.mdl"
			"61"		"models/props_c17/FurnitureWashingmachine001a.mdl"
			"62"		"models/props_c17/gravestone_cross001b.mdl"
			"63"		"models/props_c17/gravestone_statue001a.mdl"
			"64"		"models/props_c17/Lockers001a.mdl"
			"65"		"models/props_c17/oildrum001.mdl"
			"66"		"models/props_c17/shelfunit01a.mdl"
			"67"		"models/props_combine/breenchair.mdl"
			"68"		"models/props_interiors/Furniture_Couch01a.mdl"
			"69"		"models/props_interiors/Furniture_Couch02a.mdl"
			"70"		"models/props_junk/MetalBucket02a.mdl"
			"71"		"models/props_junk/metalgascan.mdl"
			"72"		"models/props_junk/PushCart01a.mdl"
			"73"		"models/props_junk/sawblade001a.mdl"
			"74"		"models/props_junk/TrashBin01a.mdl"
			"75"		"models/props_junk/TrashDumpster01a.mdl"
			"76"		"models/props_junk/wood_crate001a.mdl"
			"77"		"models/props_junk/wood_crate002a.mdl"
			"78"		"models/props_junk/wood_pallet001a.mdl"
			"79"		"models/props_lab/filecabinet02.mdl"
			"80"		"models/props_trainstation/trashcan_indoor001a.mdl"
			"81"		"models/props_trainstation/trashcan_indoor001b.mdl"
			"82"		"models/props_vehicles/tire001a_tractor.mdl"
			"83"		"models/props_vehicles/tire001b_truck.mdl"
			"84"		"models/props_vehicles/tire001c_car.mdl"
			"85"		"models/props_vehicles/apc_tire001.mdl"
			"86"		"models/props_wasteland/barricade001a.mdl"
			"87"		"models/props_wasteland/barricade002a.mdl"
			"88"		"models/props_wasteland/cargo_container01.mdl"
			"89"		"models/props_wasteland/cargo_container01b.mdl"
			"90"		"models/props_wasteland/laundry_washer003.mdl"
			"91"		"models/props_junk/garbage128_composite001a.mdl"
			"92"		"models/props_junk/garbage128_composite001b.mdl"
			"93"		"models/props_junk/garbage128_composite001c.mdl"
			"94"		"models/props_junk/garbage128_composite001d.mdl"
			"95"		"models/props_junk/garbage256_composite001a.mdl"
			"96"		"models/props_junk/garbage256_composite001b.mdl"
			"97"		"models/props_junk/garbage256_composite002a.mdl"
			"98"		"models/props_junk/garbage256_composite002b.mdl"
		}
		"icon"		"icon16/camera.png"
		"name"		"Scenery"
	}
	"7"
	{
		"tooltip"		"Broken Vehicles"
		"Models"
		{
			"1"		"models/props_canal/boat001a.mdl"
			"2"		"models/props_canal/boat001b.mdl"
			"3"		"models/props_canal/boat002b.mdl"
			"4"		"models/props_vehicles/car002a_physics.mdl"
			"5"		"models/props_vehicles/car001b_hatchback.mdl"
			"6"		"models/props_vehicles/car001a_hatchback.mdl"
			"7"		"models/props_vehicles/apc001.mdl"
			"8"		"models/props_vehicles/car002b_physics.mdl"
			"9"		"models/props_vehicles/car003a_physics.mdl"
			"10"		"models/props_vehicles/car003b_physics.mdl"
			"11"		"models/props_vehicles/car004a_physics.mdl"
			"12"		"models/props_vehicles/car004b_physics.mdl"
			"13"		"models/props_vehicles/car005a_physics.mdl"
			"14"		"models/props_vehicles/car005b_physics.mdl"
			"15"		"models/props_vehicles/tanker001a.mdl"
			"16"		"models/props_vehicles/generatortrailer01.mdl"
			"17"		"models/props_vehicles/trailer002a.mdl"
			"18"		"models/props_vehicles/truck001a.mdl"
			"19"		"models/props_vehicles/truck002a_cab.mdl"
			"20"		"models/props_vehicles/truck003a.mdl"
			"21"		"models/props_vehicles/van001a_physics.mdl"
		}
		"icon"		"icon16/car.png"
		"name"		"Vehicles"
	}
}
