
function nzQMenu.AddNewEntity( ent, icon, name )
	table.insert(nzQMenu.Data.Entities, {ent, icon, name})
end

-- QuickFunctions
PropMenuAddEntity = nzQMenu.AddNewEntity

PropMenuAddEntity("edit_fog", "entities/edit_fog.png", "Base Fog Editor")
PropMenuAddEntity("edit_fog_special", "entities/edit_fog.png", "Special Round Fog Editor")
PropMenuAddEntity("edit_sky", "entities/edit_sky.png", "Sky Editor")
PropMenuAddEntity("edit_sun", "entities/edit_sun.png", "Sun Editor")
PropMenuAddEntity("edit_color", "gmod/demo.png", "Color Correction Editor")
PropMenuAddEntity("nz_fire_effect", "icon16/fire.png", "Fire Effect")
PropMenuAddEntity("pfx8_05", "icon16/cd.png", "Ball Core")
PropMenuAddEntity("pfx8_04", "icon16/cd.png", "Core")
PropMenuAddEntity("pfx8_03", "icon16/ruby.png", "Magic Portal")
PropMenuAddEntity("pfx8_02", "icon16/fire.png", "Magic Flame")
PropMenuAddEntity("pfx8_01", "icon16/stop.png", "Red Vortex")
PropMenuAddEntity("pfx7_02", "icon16/weather_snow.png", "Snow")
PropMenuAddEntity("pfx7_01", "icon16/weather_rain.png", "Rain")
PropMenuAddEntity("pfx7_00", "icon16/weather_cloudy.png", "Wind")
PropMenuAddEntity("pfx5_01", "icon16/star.png", "Starfield")
PropMenuAddEntity("pfx5_00_s", "icon16/contrast.png", "Black Hole")
PropMenuAddEntity("pfx4_09", "icon16/pill.png", "Matrix Core")
PropMenuAddEntity("pfx4_08", "icon16/lightning.png", "Electric Beam")
PropMenuAddEntity("pfx4_06_3", "icon16/lightning.png", "Energy Rod (Yellow)")
PropMenuAddEntity("pfx4_06_2", "icon16/lightning.png", "Energy Rod (Red)")
PropMenuAddEntity("pfx4_06_1", "icon16/lightning.png", "Energy Rod (Green)")
PropMenuAddEntity("pfx4_06", "icon16/lightning.png", "Energy Rod (Blue)")
PropMenuAddEntity("pfx4_05~", "icon16/lightning.png", "Electricity Arc (Small)")
PropMenuAddEntity("pfx4_05", "icon16/lightning.png", "Electricity Arc")
PropMenuAddEntity("pfx3_01", "icon16/world.png", "Leaves")
PropMenuAddEntity("pfx3_00", "icon16/world.png", "Sakura Leaves")
PropMenuAddEntity("pfx2_03", "icon16/bug.png", "Acid Puddle")
PropMenuAddEntity("pfx1_09", "icon16/fire.png", "Gas Leak Fire")
PropMenuAddEntity("pfx1_08~", "icon16/tag_blue.png", "Small Fire (Blue)")
PropMenuAddEntity("pfx1_08_~a", "icon16/tag_purple.png", "Small Fire (Purple)")
PropMenuAddEntity("pfx1_08_~", "icon16/tag_yellow.png", "Small Fire (Yellow)")
PropMenuAddEntity("pfx1_08_", "icon16/tag_red.png", "Small Fire (Red)")
PropMenuAddEntity("pfx1_08", "icon16/tag_green.png", "Small Fire (Green)")
PropMenuAddEntity("pfx1_00", "icon16/tag_orange.png", "Small Fire")
PropMenuAddEntity("pfx1_07", "icon16/bomb.png", "Smoke Cloud")
PropMenuAddEntity("pfx1_06~", "icon16/fire.png", "Flame Stream(Large)")
PropMenuAddEntity("pfx1_06", "icon16/fire.png", "Flame Stream(Small)")
PropMenuAddEntity("pfx1_05", "icon16/fire.png", "Ground Fire")
PropMenuAddEntity("pfx1_01", "icon16/fire.png", "Ground Fire(Alt)")
PropMenuAddEntity("pfx1_0c", "icon16/fire.png", "Ground Fire(Alt 2)")
PropMenuAddEntity("pfx1_03", "icon16/fire.png", "Embers")
PropMenuAddEntity("pfx1_03", "icon16/fire.png", "Embers")
PropMenuAddEntity("pfx1_03~", "icon16/fire.png", "Embers(Secondary)")
PropMenuAddEntity("pfx1_02", "icon16/fire.png", "Molotov Fire")
PropMenuAddEntity("pfx1_0b", "icon16/fire.png", "Candle Flame")
PropMenuAddEntity("edit_dynlight", "icon16/lightbulb.png", "Dynamic Light")
--PropMenuAddEntity("edit_damage", "icon16/lightbulb.png", "Damage")