
function nzQMenu.AddNewEntity( ent, icon, name )
	table.insert(nzQMenu.Data.Entities, {ent, icon, name})
end

-- QuickFunctions
PropMenuAddEntity = nzQMenu.AddNewEntity

PropMenuAddEntity("edit_fog", "entities/edit_fog.png", "Base Fog Editor")
PropMenuAddEntity("edit_fog_special", "entities/edit_fog.png", "Special Round Fog Editor")
PropMenuAddEntity("edit_sky", "entities/edit_sky.png", "Sky Editor")
PropMenuAddEntity("edit_sun", "entities/edit_sun.png", "Sun Editor")
PropMenuAddEntity("edit_color", "gmod/demo.png", "Color Correction Editor")
PropMenuAddEntity("nz_fire_effect", "icon16/fire.png", "Fire Effect")
PropMenuAddEntity("pfx1_00", "icon16/tag_orange.png", "Fire")
PropMenuAddEntity("pfx1_08", "icon16/tag_green.png", "Fire (Green Fire)")
PropMenuAddEntity("pfx1_08_", "icon16/tag_red.png", "Fire (Red Fire)")
PropMenuAddEntity("pfx1_08_~", "icon16/tag_yellow.png", "Fire (Yellow Fire)")
PropMenuAddEntity("pfx1_08_~a", "icon16/tag_purple.png", "Fire (Purple Fire)")
PropMenuAddEntity("pfx1_08~", "icon16/tag_blue.png", "Fire (Blue Fire)")
PropMenuAddEntity("pfx1_0b", "icon16/fire.png", "Candle Flame")
PropMenuAddEntity("pfx1_0c", "icon16/fire.png", "Large Fire")
PropMenuAddEntity("pfx1_0c~", "icon16/fire.png", "Fire 2")
PropMenuAddEntity("pfx1_01", "icon16/fire.png", "Fire 3")
PropMenuAddEntity("pfx1_02", "icon16/fire.png", "Molotov Fire")
PropMenuAddEntity("pfx1_03", "icon16/fire.png", "Embers")
PropMenuAddEntity("pfx1_04", "icon16/fire.png", "Focused Fire")
PropMenuAddEntity("pfx1_05", "icon16/fire.png", "Fire 4")
PropMenuAddEntity("pfx1_06~", "icon16/fire.png", "Flamethrower")
PropMenuAddEntity("pfx1_07", "icon16/fire.png", "Smoke (Large)")
PropMenuAddEntity("pfx1_09", "icon16/fire.png", "Gasleak")
PropMenuAddEntity("pfx2_03", "icon16/world.png", "Acid Pool")
PropMenuAddEntity("pfx4_05", "icon16/lightning.png", "Electricity Arcs")
PropMenuAddEntity("pfx4_05~", "icon16/lightning.png", "Electricity Arcs (Small)")
PropMenuAddEntity("pfx4_08", "icon16/lightning.png", "Electric Beam")
PropMenuAddEntity("pfx4_09", "icon16/color_wheel.png", "Core")
PropMenuAddEntity("pfx8_05", "icon16/color_wheel.png", "Core 2")
PropMenuAddEntity("pfx5_00", "icon16/contrast.png", "Black Hole")
PropMenuAddEntity("pfx5_00_alt", "icon16/contrast.png", "Black Hole 2")
PropMenuAddEntity("pfx5_00_ss", "icon16/contrast.png", "Black Hole (Small)")
PropMenuAddEntity("pfx7_00", "entities/edit_fog.png", "Dusty Wind")
PropMenuAddEntity("pfx7_01", "entities/edit_fog.png", "Rain")
PropMenuAddEntity("pfx7_02", "entities/edit_fog.png", "Snow")
PropMenuAddEntity("pfx8_01", "icon16/color_wheel.png", "Red Vortex")
PropMenuAddEntity("pfx8_03", "icon16/color_wheel.png", "Magic Portal")
PropMenuAddEntity("edit_dynlight", "icon16/lightbulb.png", "Dynamic Light")
--PropMenuAddEntity("edit_damage", "icon16/lightbulb.png", "Damage")